# Generated by Django 4.1.5 on 2023-02-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
